"""empty message

Revision ID: d318e08d8169
Revises: 01e28de48a38
Create Date: 2022-02-07 04:17:32.126565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd318e08d8169'
down_revision = '01e28de48a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_hash', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_hash')
    # ### end Alembic commands ###
